import { GatewayMonitorItem } from "./types";

export const gatewayMonitorDummy: GatewayMonitorItem[] = [
  {
    bpr_id: "459085218",
    nama_bpr: "BPR Dana Arta",
    gateway_url: "https://gateway-dana-arta.example.com",
    status: "ERROR",
    reason: "Endpoint echo tidak merespons",
    checked_at: "22-04-2026 23:18:10",
    echo_success: false,
  },
  {
    bpr_id: "69733318",
    nama_bpr: "BPR MTD Sejahtera",
    gateway_url: "https://gateway-mtd-sejahtera.example.com",
    status: "ERROR",
    reason: "Timeout saat hit endpoint echo",
    checked_at: "22-04-2026 23:18:10",
    echo_success: false,
  },
  {
    bpr_id: "459085218-2",
    nama_bpr: "BPR Nusantara",
    gateway_url: "https://gateway-nusantara.example.com",
    status: "ERROR",
    reason: "Response endpoint echo gagal",
    checked_at: "22-04-2026 23:18:10",
    echo_success: false,
  },
  {
    bpr_id: "600931",
    nama_bpr: "BPR Medtrans",
    gateway_url: "https://gateway-medtrans.example.com",
    status: "NORMAL",
    reason: "Echo success",
    checked_at: "22-04-2026 23:18:10",
    echo_success: true,
  },
  {
    bpr_id: "609999",
    nama_bpr: "BPR MTD",
    gateway_url: "https://gateway-testing.example.com",
    status: "NORMAL",
    reason: "Echo success",
    checked_at: "22-04-2026 23:18:10",
    echo_success: true,
  },
  {
    bpr_id: "600777",
    nama_bpr: "BPR Sentosa",
    gateway_url: "https://gateway-sentosa.example.com",
    status: "WARNING",
    reason: "Response echo lambat namun masih berhasil",
    checked_at: "22-04-2026 23:18:10",
    echo_success: true,
  },
  {
    bpr_id: "600888",
    nama_bpr: "BPR Harmoni",
    gateway_url: "https://gateway-harmoni.example.com",
    status: "OFFLINE",
    reason: "Gateway dinonaktifkan sementara",
    checked_at: "22-04-2026 23:18:10",
    echo_success: false,
  },
];